# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  # Strix Halo (Ryzen AI MAX+ 395 / Radeon 8060S) GPU memory & IOMMU tuning.
  #
  # Strategy: unified memory. The BIOS "GPU memory" allocation is set to the
  # minimum (512 MiB), so the iGPU draws up to 124 GiB of *system* RAM on demand
  # through the GTT, instead of a permanently carved-out 64 GiB that the CPU can
  # never see.
  #
  # The two caps are partners:
  #   - amdgpu.gttsize caps what the amdgpu driver may allocate as GTT (MiB).
  #   - ttm.pages_limit caps what the kernel DRM memory manager may pin
  #     (pages x 4 KiB), enforcing the same budget at the lower layer.
  # Both must agree or allocation fails.
  #
  # amd_iommu=off removes per-DMA page-table translation for unified-memory
  # traffic (measured 5-12% faster than iommu=pt; see kyuz0/amd-strix-halo-toolboxes
  # issue #66). Tradeoff: no DMA isolation and no VFIO passthrough.
  #
  # Reference: https://github.com/kyuz0/amd-strix-halo-toolboxes#host-configuration
  # (tested on Framework Desktop, Ryzen AI MAX+ 395, 128 GB RAM, 512 MiB BIOS carve-out)
  #
  # Headroom note: this caps the GPU at 124 GiB, leaving ~4 GiB of RAM guaranteed
  # for the OS at the extreme. A desktop running niri + k3s + docker may prefer
  # ~110 GiB (gttsize=112640, pages_limit=28835840) if huge-model runs ever starve
  # the OS; tune consciously.
  boot.kernelParams = [
    "amd_iommu=off"
    "amdgpu.gttsize=126976"
    "ttm.pages_limit=32505856"
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/bde5d350-66d2-4939-9090-bb7f607a2bfc";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DA59-E937";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-label/data";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4a92ceb9-b823-4527-ae29-1626e1c241e3"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
